### ISSUE TITLE
Second video is fuzzy

### ISSUE THREAD

**Issue by WilliamJones62** [learn-co-curriculum/oo-ruby-video-review-object-orientation-and-scraping#1]
It is difficult to read what is typed on the screen.

**Comment by curiositypaths** [comment]
Hi there, 

Thank you for notifying us about the issue. You should be able to play the file in high definition (720p), and the text should be legible.

If for any reason the internet connection is running slow YouTube will scale down the quality of the video to allow it to play.

Thanks! 💙
