### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by DoriansGrave** [learn-co-curriculum/oo-ruby-video-review-object-orientation-and-scraping#2]
The code for these videos needs to be provided every time and updated. Without the ability to interact, anything that doesn't work goes completely unexplained. And if that code can't be fixed the entire lesson is pointless. The fact that some of these lessons (like this one) use public sites to construct their code makes it impossible to guarantee that anything will work after the video is published. If I cannot build a working custom constructor with the code in this video (because the public site's code has since changed) and I can't figure out how to update it to work with the new information, I learn nothing. Please update the outdated information in the curriculum.

**Comment by DanielSeehausen** [comment]
Hi there,

We appreciate your feedback and thank you for bringing this to our attention. These videos are designed to supplement code-along material that is provided in other labs and readmes. I will review the videos tomorrow and, if the information within is no longer relevant, will discuss with the team how to improve it. 

This issue would be perfect for the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out if you are having trouble following content in the video. 

Thanks! 💙
